session_name: ANALYSIS_AGENTS
suppress_history: false
start_directory: ../
global_options:
  default-shell: /bin/bash
  default-command: /bin/bash
environment:
  EDITOR: /bin/nano
windows:
- window_name: analysis_agents
  focus: true
  layout: tiled
  panes:
    - shell_command:
      - xhost +
      - ./up_eval.sh
    - shell_command:
      - sleep 5
      - ./into.sh
      - roslaunch rl_bringup rviz.launch ns:="sim1"
    - shell_command:
      - sleep 5
      - ./into.sh
      - roslaunch rl_bringup setup.launch ns:="sim1" rl_params:="rl_params_scan"
    - shell_command:
      # - conda activate ds
      - tensorboard --logdir ../../data/tensorboard_eval
    - shell_command:
      - sleep 10
      - ./into.sh
      - source /venv_p3/bin/activate 
      - rosrun rl_agent analysis.py 