version: "3.8"
services:
    drl_local_planner:
        image: ${ARCH}melodic/drl_local_planner:${TAG}
        build:
            context: ${PRODUCTION_PATH}/drl_local_planner_ros_stable_baselines/docker
            dockerfile: Dockerfile
        container_name: drl_local_planner
        volumes:
            - type: bind
              source: ${PRODUCTION_PATH}/drl_local_planner_ros_stable_baselines
              target: /usr/catkin_ws/src/drl_local_planner_ros_stable_baselines
        command: bash -c "source /opt/ros/melodic/setup.sh;
                          cd catkin_ws;
                          catkin_make;
                          sleep ${POST_BUILD_SLEEP};"
